### ISSUE TITLE
Sntiches aren't refreshed while in vehicles

### ISSUE THREAD

**Issue by wingzero54** [CivMC/JukeAlert#2]

**Comment by Diet-Cola** [comment]
Needs further testing, players moving in a vehicle trigger the same code as players walking into fields

**Comment by Gjum** [comment]
is the player position updated while moving in a vehicle? iirc while in certain vehicles the player position stays at where they entered the vehicle, and only the vehicle entity position is updated; only when the player exits the vehicle is the player position updated to the exit location. if this is still true, a fix would be to special-case players in vehicles and using the vehicle location instead of the player location for checking snitch ranges.

**Comment by wingzero54** [comment]
See: https://github.com/CivClassic/JukeAlert/issues/53. Original issue by KaloHG claiming boating did not refresh their snitches. Metriximor theorized it may be because vehicles have a different entry event.

Definitely needs testing as it is very possible KaloHG was mistaken. At one point /jalist was not updating live and so a refreshed snitch did not show as refreshed until the next day, so that could have been the cause.

**Comment by Maxopoly** [comment]
Requesting someone to actually reproduce this, looking at the code I'm relatively sure it should work. Metriximor's analysis in the original issue is wrong, he's looking at the wrong place.

**Comment by wingzero54** [comment]
Issue was created before a ton of performance improvements and optimizations to JA by Orinnari, plus no replication of issue
